### ISSUE TITLE
Constructor for Workspace class

### ISSUE THREAD

**Issue by gris** [ChristianEder/structurizr-typescript#14]
Hey, @ChristianEder, do you think it would be a good idea to have a constructor in the workspace [class](https://github.com/ChristianEder/structurizr-typescript/blob/master/src/core/model/workspace.ts#L39)? Like the one in the Java [client](https://github.com/structurizr/java/blob/master/structurizr-examples/src/com/structurizr/example/GettingStarted.java#L28)

Best

**Comment by ChristianEder** [comment]
Hi @gris - I at least wouldn't think its a bad idea :-) Until now, I didn't add it because I didn't think it adds a whole lot of value, but I wouldn't object to it being added.

Best
