### ISSUE TITLE
Export components in PlantUML

### ISSUE THREAD

**Issue by threkk** [ChristianEder/structurizr-typescript#17]
Currently, my components views are not exported in PlantUML. As far as a I can see at https://github.com/ChristianEder/structurizr-typescript/blob/master/src/client/plantUML/plantUMLWriter.ts#L27, there is no trace of the components in the exporter. Is this going to be fixed soon?

**Comment by ChristianEder** [comment]
Hi @threkk - just a brief heads up, I didn't forget you, but pretty much under load right now, will get back to this and have a look into how this is solved in the other SDKs like C# and Java. I'm always happy to receive PRs 🙂

**Comment by ChristianEder** [comment]
fixed in version 1.0.8
