### ISSUE TITLE
Implied Relationship Stratergies

### ISSUE THREAD

**Issue by toddpla** [ChristianEder/structurizr-typescript#21]
Just wondering whether there are plans to add functionality to handle the Implied Relationship Strategies?

**Comment by ChristianEder** [comment]
Sorry for the late response - holidays came in between :-)

I wasn't aware of that feature in the Java SDK - looks neat, will try to add it, but probably will not be able to get at it before next month...

**Comment by ChristianEder** [comment]
Implemented in version 1.0.10
