### ISSUE TITLE
Property 'configuration' does not exist on type 'ViewSet'

### ISSUE THREAD

**Issue by trocho** [ChristianEder/structurizr-typescript#4]
Hi,

I've got an error. I checked the sources but everything seems good. Maybe something with the deployment process or the npm repository?

![Zaznaczenie_164](https://user-images.githubusercontent.com/9249585/67089426-cf399280-f1a7-11e9-91c1-059258fd2d8f.png)

**Comment by ChristianEder** [comment]
Hi,

Thanks for bringing this up. I’ll have a look into it on Monday and try to provide a fix

**Comment by ChristianEder** [comment]
Looks like I made an error when publishing version 0.0.13. I just republished, which seems to fix the issue.

Please update to 0.0.14, this should solve your issue.

**Comment by ChristianEder** [comment]
Sure - thanks for reporting, always happy to see when my stuff is getting used :-)

**Comment by trocho** [comment]
Yeah :) Good job. Keep going :)
